theme: minima
title: pyDCMvn
description: Python DICOM Library for Vietnamese Healthcare
url: "https://diggtvu.github.io"
baseurl: "/pyDCMvnDocs"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: API Reference
    url: /api-reference
  - title: Examples
    url: /examples
  - title: Contributing
    url: /contributing
  - title: GitHub
    url: https://github.com/yourusername/pyDCMvn

# Social links
github_username: yourusername

# SEO
author: pyDCMvn Team
twitter:
  username: pydcmvn
  card: summary

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
