name: Build and Deploy Docusaurus

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'DEPLOYMENT*.md'
  pull_request:
    branches:
      - main

jobs:
  # Test job for pull requests and main branch pushes
  test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test build website
        run: npm run build

      - name: Test serve (basic check)
        run: |
          npm run serve &
          SERVER_PID=$!
          sleep 10
          # Basic connectivity test
          curl -f http://localhost:3000/pyDCMvnDocs/ || (echo "Server test failed" && kill $SERVER_PID && exit 1)
          kill $SERVER_PID

  # Deploy job - only runs on main branch pushes
  deploy:
    name: Build and Deploy to gh-pages-deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    # Configure GitHub Pages deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url || format('https://{0}.github.io/{1}', 'diggtvu', 'pyDCMvnDocs') }}
    
    permissions:
      contents: write  # to push to gh-pages-deploy branch
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: |
          npm run build
          touch ./build/.nojekyll

      - name: Deploy to gh-pages-deploy branch
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages-deploy
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Docusaurus site - ${{ github.sha }}'
          
      # Explicitly update GitHub Pages to use gh-pages-deploy branch
      - name: Set GitHub Pages branch (informational only)
        run: |
          echo "GitHub Pages should be configured to use the gh-pages-deploy branch"
          echo "Please verify this setting in your repository's Settings > Pages section"